name: Manage Codespaces

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start or stop)'
        required: true
        default: 'start'
      codespace_name:
        description: 'Name of the codespace to start/stop. If left blank, the first codespace will be used if only one is available.'
        required: false

jobs:
  manage-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token ${{ secrets.GH_TOKEN }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Determine Codespace to Manage
        id: determine_codespace
        run: |
          codespaces=$(gh codespace list --repo ${{ github.repository }} --json name)
          codespace_count=$(echo "$codespaces" | jq 'length')
          echo "Codespace count: $codespace_count"
          
          # If no codespace name is provided and there is only one codespace, select it automatically.
          if [ -z "${{ github.event.inputs.codespace_name }}" ] && [ "$codespace_count" -eq 1 ]; then
            codespace_name=$(echo "$codespaces" | jq -r '.[0].name')
            echo "::set-output name=selected_codespace::$codespace_name"
          elif [ -z "${{ github.event.inputs.codespace_name }}" ] && [ "$codespace_count" -gt 1 ]; then
            echo "Please specify a codespace name. Available codespaces:"
            echo "$codespaces" | jq -r '.[].name'
            exit 1
          else
            echo "::set-output name=selected_codespace::${{ github.event.inputs.codespace_name }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Start Codespace
        if: ${{ github.event.inputs.action == 'start' }}
        run: gh codespace code --codespace ${{ steps.determine_codespace.outputs.selected_codespace }}

      - name: Stop Codespace
        if: ${{ github.event.inputs.action == 'stop' }}
        run: gh codespace stop --codespace ${{ steps.determine_codespace.outputs.selected_codespace }}
