name: Codespace Management Workflow

on:
  workflow_dispatch:
    inputs:
      codespace_action:
        description: 'Action to perform: start or stop'
        required: true
      codespace_name:
        description: 'Name of the Codespace to manage (leave blank to auto-detect if there is only one)'
        required: false

jobs:
  manage_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get list of codespaces
        id: list_codespaces
        run: |
          codespaces_list=$(gh codespace list -q ".[].name")
          echo "::set-output name=codespaces_list::$codespaces_list"
        shell: bash

      - name: Determine codespace to manage
        id: determine_codespace
        run: |
          codespace_name="${{ github.event.inputs.codespace_name }}"
          if [[ -z "$codespace_name" ]]; then
            IFS=' ' read -r -a codespace_array <<< "${{ steps.list_codespaces.outputs.codespaces_list }}"
            if [[ ${#codespace_array[@]} -eq 1 ]]; then
              codespace_name=${codespace_array[0]}
            else
              echo "More than one codespace available, please specify the codespace name."
              echo "::set-output name=selected_codespace::"
              exit 1
            fi
          fi
          echo "Selected Codespace: $codespace_name"
          echo "::set-output name=selected_codespace::$codespace_name"
        shell: bash

      - name: Start or Stop Codespace
        if: steps.determine_codespace.outputs.selected_codespace != ''
        run: |
          action="${{ github.event.inputs.codespace_action }}"
          codespace_name="${{ steps.determine_codespace.outputs.selected_codespace }}"
          if [ "$action" == "start" ]; then
            gh codespace start -c "$codespace_name"
          elif [ "$action" == "stop" ]; then
            gh codespace stop -c "$codespace_name"
          else
            echo "Invalid action specified: $action"
            exit 1
          fi
        shell: bash
      - name: Print completion message
        run: echo "Workflow completed successfully!"
