name: Start Codespace

on:
  workflow_dispatch:

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
    - name: Start Codespace
      run: |
        gh auth login --with-token ${{ secrets.GH_TOKEN }}
        gh codespace code <repository>
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
